/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DroneRepairsRouteImport } from './routes/drone-repairs'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SendPackageRouteImport } from './routes/send-package'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VendorsRouteImport } from './routes/vendors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DroneRepairsRoute = DroneRepairsRouteImport.update({
  id: '/drone-repairs',
  path: '/drone-repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SendPackageRoute = SendPackageRouteImport.update({
  id: '/send-package',
  path: '/send-package',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/drone-repairs': typeof DroneRepairsRoute
  '/photography': typeof PhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/send-package': typeof SendPackageRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/drone-repairs': typeof DroneRepairsRoute
  '/photography': typeof PhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/send-package': typeof SendPackageRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/drone-repairs': typeof DroneRepairsRoute
  '/photography': typeof PhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/send-package': typeof SendPackageRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/career'
    | '/contact'
    | '/drone-repairs'
    | '/photography'
    | '/privacy'
    | '/send-package'
    | '/technology'
    | '/terms'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/career'
    | '/contact'
    | '/drone-repairs'
    | '/photography'
    | '/privacy'
    | '/send-package'
    | '/technology'
    | '/terms'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/career'
    | '/contact'
    | '/drone-repairs'
    | '/photography'
    | '/privacy'
    | '/send-package'
    | '/technology'
    | '/terms'
    | '/vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  DroneRepairsRoute: typeof DroneRepairsRoute
  PhotographyRoute: typeof PhotographyRoute
  PrivacyRoute: typeof PrivacyRoute
  SendPackageRoute: typeof SendPackageRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drone-repairs': {
      id: '/drone-repairs'
      path: '/drone-repairs'
      fullPath: '/drone-repairs'
      preLoaderRoute: typeof DroneRepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-package': {
      id: '/send-package'
      path: '/send-package'
      fullPath: '/send-package'
      preLoaderRoute: typeof SendPackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  DroneRepairsRoute: DroneRepairsRoute,
  PhotographyRoute: PhotographyRoute,
  PrivacyRoute: PrivacyRoute,
  SendPackageRoute: SendPackageRoute,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
